### PR TITLE
Add section on team for blockchain developer and general counsel

### PR DESCRIPTION
**Pull request by hskang9**
# Team Overview
https://www.useloom.com/share/50f76e02895144b3acfbd9b889948149

### CODE REVIEW

**Comment by lingqingmeng** [comment]
css needs work

**Comment by hskang9** [comment]
Fix CSS:

- On Monika's width and height:
width: 30% of browser length
height: 1015px
border: 5px

I applied the same css for each cards using the variable.

**Comment by lingqingmeng** [comment]
also, please change Monika -> Monica

**Comment by hskang9** [comment]
Merging it with confirmation

**Pull request merged**
